import { flag, moveTo, numericNodes, type AiConceptDefinition, type AiConceptValueType, type AiConceptCategory, type AiConceptMapFocus, type AiConceptReadiness } from './AiConceptTypes';
import type { AiBlackboardValue } from './AiBlackboard';

type ValueArgs = {
  key: string; label: string; ru: string; description: string; descriptionRu: string;
  type: AiConceptValueType; category: AiConceptCategory; readiness?: AiConceptReadiness;
  limitation?: string; limitationRu?: string; source: string; sourceRu: string;
  defaultValue: AiBlackboardValue; mapFocus?: AiConceptMapFocus; nodes?: 'numeric' | 'flag' | 'move' | 'none';
  minimum?: number; maximum?: number; aliases?: readonly string[];
};

function value(args: ValueArgs): AiConceptDefinition {
  const readiness = args.readiness ?? 'ready';
  const defaultReady = 'The runtime value is available to the graph and dictionary.';
  const defaultReadyRu = 'Текущее значение доступно графу и словарю.';
  return {
    key: args.key, kind: 'value', category: args.category, valueType: args.type,
    label: args.label, labelRu: args.ru, description: args.description, descriptionRu: args.descriptionRu,
    readiness, readinessExplanation: args.limitation ?? defaultReady, readinessExplanationRu: args.limitationRu ?? defaultReadyRu,
    source: args.source, sourceRu: args.sourceRu, defaultValue: args.defaultValue,
    minimum: args.minimum, maximum: args.maximum, mapFocus: args.mapFocus ?? 'unit', aliases: args.aliases,
    nodeTemplates: args.nodes === 'numeric' ? numericNodes(args.key) : args.nodes === 'flag' ? [flag(args.key)] : args.nodes === 'move' ? [moveTo(args.key)] : [],
  };
}

const threatSimplified = 'Uses threat zones rather than complete projectile and enemy-weapon simulation.';
const threatSimplifiedRu = 'Использует зоны угроз, а не полную симуляцию пуль и оружия противника.';
const exposed = 'The value already existed and is now exposed to human node controls.';
const exposedRu = 'Значение уже существовало и теперь доступно в понятных настройках нод.';
const trait = (key: string, label: string, ru: string, description: string, descriptionRu: string) => value({
  key, label, ru, description, descriptionRu, type: 'percent', category: 'soldier', readiness: 'hidden',
  limitation: exposed, limitationRu: exposedRu, source: 'Soldier traits', sourceRu: 'Постоянные характеристики бойца',
  defaultValue: 50, minimum: 0, maximum: 100, nodes: 'numeric',
});
const condition = (key: string, label: string, ru: string, description: string, descriptionRu: string, readiness: AiConceptReadiness = 'ready') => value({
  key, label, ru, description, descriptionRu, type: 'percent', category: 'condition', readiness,
  limitation: readiness === 'hidden' ? exposed : undefined, limitationRu: readiness === 'hidden' ? exposedRu : undefined,
  source: 'Soldier condition', sourceRu: 'Текущее состояние бойца', defaultValue: 0, minimum: 0, maximum: 100, nodes: 'numeric',
});

export const AI_VALUE_CONCEPTS: readonly AiConceptDefinition[] = [
  value({ key:'danger', label:'Immediate danger', ru:'Опасность прямо сейчас', description:'Immediate danger from active threats, distance, posture and cover.', descriptionRu:'Мгновенная опасность от активных угроз с учётом расстояния, позы и укрытия.', type:'percent', category:'danger', readiness:'simplified', limitation:threatSimplified, limitationRu:threatSimplifiedRu, source:'ThreatEvaluation', sourceRu:'Оценка текущих угроз', defaultValue:0, minimum:0, maximum:100, mapFocus:'threat', nodes:'numeric' }),
  condition('stress','Stress','Стресс','Current internal combat stress.','Текущее внутреннее боевое напряжение.'),
  value({ key:'suppression', label:'Suppression', ru:'Подавление', description:'How strongly incoming fire prevents normal action.', descriptionRu:'Насколько входящий огонь мешает нормально действовать.', type:'percent', category:'danger', readiness:'simplified', limitation:threatSimplified, limitationRu:threatSimplifiedRu, source:'ThreatEvaluation', sourceRu:'Оценка текущих угроз', defaultValue:0, minimum:0, maximum:100, mapFocus:'threat', nodes:'numeric' }),
  condition('fatigue','Fatigue','Усталость','Current physical fatigue.','Текущая физическая усталость.'),
  condition('morale','Morale','Боевой дух','Willingness to keep acting under pressure.','Готовность продолжать действовать под давлением.'),
  condition('health','Health','Здоровье','Current physical health.','Текущее физическое здоровье.','simplified'),
  value({ key:'ammo', label:'Ammunition', ru:'Патроны', description:'Current useful ammunition count.', descriptionRu:'Текущее количество доступных патронов.', type:'number', category:'condition', readiness:'simplified', limitation:'Firing consumes rounds and reload restores a fixed magazine.', limitationRu:'Стрельба расходует патроны, а перезарядка пока восстанавливает фиксированный магазин.', source:'Behavior runtime', sourceRu:'Текущее состояние оружия', defaultValue:30, minimum:0, nodes:'numeric' }),
  value({ key:'distanceToCover', label:'Distance to cover', ru:'Расстояние до укрытия', description:'Distance to the selected cover candidate.', descriptionRu:'Расстояние до выбранной точки укрытия.', type:'meters', category:'cover', source:'Cover evaluation', sourceRu:'Поиск укрытий', defaultValue:9999, minimum:0, mapFocus:'cover', nodes:'numeric' }),
  value({ key:'enemyVisible', label:'Enemy visible', ru:'Враг виден', description:'Whether the best subjective contact is visually identified right now.', descriptionRu:'Опознан ли лучший субъективный контакт зрительно прямо сейчас.', type:'boolean', category:'perception', source:'Perception knowledge', sourceRu:'Личное восприятие бойца', defaultValue:false, mapFocus:'threat', nodes:'flag' }),
  value({ key:'enemyKnown', label:'Enemy known', ru:'Враг известен', description:'Whether the soldier has a subjective visual, sound, reported, or fire-pressure contact.', descriptionRu:'Есть ли у бойца субъективный зрительный, звуковой, переданный или понятый по обстрелу контакт.', type:'boolean', category:'perception', source:'Perception knowledge', sourceRu:'Личная память контактов бойца', defaultValue:false, mapFocus:'memory', nodes:'flag' }),
  value({ key:'underFire', label:'Under fire', ru:'Под огнём', description:'True when immediate danger or suppression is above zero.', descriptionRu:'Да, когда мгновенная опасность или подавление больше нуля.', type:'boolean', category:'danger', readiness:'simplified', limitation:'This is an influence-zone flag, not a per-projectile sensor.', limitationRu:'Это флаг воздействия зоны огня, а не датчик отдельных пуль.', source:'AiGameBridge', sourceRu:'Опасность или подавление', defaultValue:false, mapFocus:'threat', nodes:'flag' }),
  value({ key:'hasOrder', label:'Has order', ru:'Есть приказ', description:'Whether the soldier has a current order.', descriptionRu:'Есть ли у бойца текущий приказ.', type:'boolean', category:'order', source:'Unit order', sourceRu:'Текущий приказ', defaultValue:false, mapFocus:'route', nodes:'flag' }),
  value({ key:'isInCover', label:'In cover', ru:'В укрытии', description:'Whether current protection is above zero.', descriptionRu:'Есть ли у текущей позиции защита больше нуля.', type:'boolean', category:'cover', readiness:'simplified', limitation:'Any positive protection enables the flag; use numeric protection for quality.', limitationRu:'Флаг включается при любой защите выше нуля; качество лучше проверять числом.', source:'Cover evaluation', sourceRu:'Оценка текущего укрытия', defaultValue:false, mapFocus:'cover', nodes:'flag' }),
  value({ key:'weaponReady', label:'Weapon ready', ru:'Оружие готово', description:'Whether the weapon is ready and ammunition remains.', descriptionRu:'Готово ли оружие и остались ли патроны.', type:'boolean', category:'condition', readiness:'simplified', limitation:'Uses a simple ready flag and ammunition count.', limitationRu:'Использует простой флаг готовности и количество патронов.', source:'Behavior runtime', sourceRu:'Текущее состояние оружия', defaultValue:true, nodes:'flag' }),
  value({ key:'directionToThreat', label:'Direction to threat', ru:'Направление на угрозу', description:'Bearing from the soldier to the strongest active threat.', descriptionRu:'Направление от бойца к самой сильной активной угрозе.', type:'degrees', category:'danger', source:'ThreatEvaluation', sourceRu:'Самая сильная угроза', defaultValue:-1, minimum:-1, maximum:360, mapFocus:'threat', nodes:'numeric' }),
  value({ key:'threatDistance', label:'Threat distance', ru:'Расстояние до угрозы', description:'Distance to the strongest active threat.', descriptionRu:'Расстояние до самой сильной активной угрозы.', type:'meters', category:'danger', source:'ThreatEvaluation', sourceRu:'Самая сильная угроза', defaultValue:9999, minimum:0, mapFocus:'threat', nodes:'numeric' }),
  value({ key:'threatAngle', label:'Threat sector angle', ru:'Ширина сектора угрозы', description:'Angular width of the strongest directional threat.', descriptionRu:'Угловая ширина сектора самой сильной направленной угрозы.', type:'degrees', category:'danger', source:'Threat zone', sourceRu:'Геометрия зоны угрозы', defaultValue:0, minimum:0, maximum:360, mapFocus:'threat', nodes:'numeric' }),
  value({ key:'coverProtection', label:'Current cover protection', ru:'Защита текущего укрытия', description:'Expected protection against the strongest active threat.', descriptionRu:'Ожидаемая защита от самой сильной активной угрозы.', type:'percent', category:'cover', source:'Small-arms cover evaluation', sourceRu:'Оценка укрытия от стрелкового оружия', defaultValue:0, minimum:0, maximum:100, mapFocus:'cover', nodes:'numeric' }),
  value({ key:'bestCoverQuality', label:'Best cover quality', ru:'Качество лучшего укрытия', description:'Score of the best physical cover candidate.', descriptionRu:'Оценка лучшего найденного физического укрытия.', type:'number', category:'cover', source:'Cover search', sourceRu:'Поиск укрытий', defaultValue:0, minimum:0, mapFocus:'cover', nodes:'numeric' }),
  value({ key:'currentPositionDanger', label:'Perceived danger here', ru:'Опасность текущей позиции по мнению бойца', description:'Danger of the current cell according to personal knowledge.', descriptionRu:'Опасность текущей клетки по личным знаниям бойца.', type:'percent', category:'danger', readiness:'hidden', limitation:exposed, limitationRu:exposedRu, source:'Soldier awareness grid', sourceRu:'Личная тактическая карта бойца', defaultValue:0, minimum:0, maximum:100, mapFocus:'unit', nodes:'numeric' }),
  value({ key:'currentExpectedProtection', label:'Expected protection here', ru:'Ожидаемая защита текущей позиции', description:'Expected protection of the current cell.', descriptionRu:'Ожидаемая защита текущей клетки.', type:'percent', category:'cover', readiness:'hidden', limitation:exposed, limitationRu:exposedRu, source:'Soldier awareness grid', sourceRu:'Личная тактическая карта бойца', defaultValue:0, minimum:0, maximum:100, mapFocus:'cover', nodes:'numeric' }),
  value({ key:'bestSafePositionScore', label:'Best safe position score', ru:'Оценка лучшей безопасной позиции', description:'Combined score of danger, protection, concealment, uncertainty and distance.', descriptionRu:'Общая оценка опасности, защиты, маскировки, неопределённости и расстояния.', type:'number', category:'cover', readiness:'hidden', limitation:exposed, limitationRu:exposedRu, source:'Soldier awareness grid', sourceRu:'Личная тактическая карта бойца', defaultValue:0, minimum:0, mapFocus:'cover', nodes:'numeric' }),
  value({ key:'distanceToBestSafePosition', label:'Distance to best safe position', ru:'Расстояние до лучшей безопасной позиции', description:'Distance to the best awareness-map position.', descriptionRu:'Расстояние до лучшей позиции личной тактической карты.', type:'meters', category:'cover', readiness:'hidden', limitation:exposed, limitationRu:exposedRu, source:'Soldier awareness grid', sourceRu:'Личная тактическая карта бойца', defaultValue:9999, minimum:0, mapFocus:'cover', nodes:'numeric' }),
  value({ key:'routeDanger', label:'Route danger', ru:'Опасность маршрута', description:'Average perceived danger along the current ordered route.', descriptionRu:'Средняя субъективная опасность пути к точке приказа.', type:'percent', category:'route', readiness:'hidden', limitation:exposed, limitationRu:exposedRu, source:'Soldier awareness grid', sourceRu:'Личная тактическая карта бойца', defaultValue:0, minimum:0, maximum:100, mapFocus:'route', nodes:'numeric' }),
  value({ key:'threatConfidence', label:'Threat confidence', ru:'Уверенность в сведениях об угрозе', description:'Highest confidence among threats in personal memory.', descriptionRu:'Наибольшая уверенность среди угроз в личной памяти.', type:'percent', category:'memory', readiness:'hidden', limitation:exposed, limitationRu:exposedRu, source:'Threat memory', sourceRu:'Личная память угроз бойца', defaultValue:0, minimum:0, maximum:100, mapFocus:'memory', nodes:'numeric' }),
  value({ key:'attention_mode', label:'Attention mode', ru:'Режим внимания', description:'Current march, observation, search, or engagement attention mode.', descriptionRu:'Текущий режим внимания: марш, наблюдение, поиск цели или стрельба.', type:'text', category:'perception', source:'Attention runtime', sourceRu:'Текущее управление вниманием', defaultValue:'observe' }),
  value({ key:'attention_focus_direction', label:'Attention focus direction', ru:'Направление фокуса внимания', description:'Current direction of the narrow attention focus.', descriptionRu:'Текущее направление узкого фокуса внимания.', type:'degrees', category:'perception', source:'Attention runtime', sourceRu:'Текущее управление вниманием', defaultValue:0, minimum:0, maximum:360, mapFocus:'unit', nodes:'numeric' }),
  value({ key:'best_contact_stage', label:'Best contact stage', ru:'Стадия лучшего контакта', description:'Cue, suspicion, contact, identified, or confirmed stage of the best subjective contact.', descriptionRu:'Стадия лучшего субъективного контакта: признак, подозрение, контакт, опознано или подтверждено.', type:'text', category:'perception', source:'Perception knowledge', sourceRu:'Личная память контактов бойца', defaultValue:'none' }),
  value({ key:'best_contact_confidence', label:'Best contact confidence', ru:'Уверенность в лучшем контакте', description:'Confidence in the best subjective contact.', descriptionRu:'Уверенность бойца в лучшем субъективном контакте.', type:'percent', category:'perception', source:'Perception knowledge', sourceRu:'Личная память контактов бойца', defaultValue:0, minimum:0, maximum:100, mapFocus:'memory', nodes:'numeric' }),
  value({ key:'best_contact_uncertainty', label:'Best contact uncertainty', ru:'Неточность лучшего контакта', description:'Estimated positional uncertainty of the best contact in meters.', descriptionRu:'Оценочная неточность положения лучшего контакта в метрах.', type:'meters', category:'perception', source:'Perception knowledge', sourceRu:'Личная память контактов бойца', defaultValue:0, minimum:0, mapFocus:'memory', nodes:'numeric' }),
  value({ key:'contact_visible_now', label:'Contact visible now', ru:'Контакт виден сейчас', description:'Whether the best contact is visually identified at this moment.', descriptionRu:'Опознан ли лучший контакт зрительно в данный момент.', type:'boolean', category:'perception', source:'Perception knowledge', sourceRu:'Личное восприятие бойца', defaultValue:false, mapFocus:'threat', nodes:'flag' }),
  value({ key:'suspected_enemy_position', label:'Suspected enemy position', ru:'Предполагаемая позиция врага', description:'Last known or estimated position of the best subjective contact.', descriptionRu:'Последняя известная или предполагаемая позиция лучшего субъективного контакта.', type:'position', category:'perception', source:'Perception knowledge', sourceRu:'Личная память контактов бойца', defaultValue:null, mapFocus:'memory' }),
  value({ key:'current_action', label:'Current action', ru:'Текущее действие', description:'Last action selected by the graph.', descriptionRu:'Последнее действие, выбранное графом.', type:'action', category:'decision', source:'Behavior runtime', sourceRu:'Исполнение решения ИИ', defaultValue:'wait', aliases:['currentAction'] }),
  value({ key:'self_position', label:'Soldier position', ru:'Позиция бойца', description:'Current selected-soldier position.', descriptionRu:'Текущая позиция выбранного бойца.', type:'position', category:'soldier', source:'Unit model', sourceRu:'Положение бойца на карте', defaultValue:null, mapFocus:'unit', aliases:['selfPosition'] }),
  value({ key:'order_target_position', label:'Order target position', ru:'Точка приказа', description:'Target point of the current order.', descriptionRu:'Целевая точка текущего приказа.', type:'position', category:'order', source:'Unit order', sourceRu:'Текущий приказ', defaultValue:null, mapFocus:'route', nodes:'move', aliases:['orderTargetPosition'] }),
  value({ key:'retreat_position', label:'Retreat position', ru:'Точка отхода', description:'A simple point away from the current threat.', descriptionRu:'Простая точка в направлении от текущей угрозы.', type:'position', category:'route', readiness:'simplified', limitation:'A short offset, not a full retreat-route planner.', limitationRu:'Короткое смещение, а не полноценный планировщик отхода.', source:'AiGameBridge', sourceRu:'Простой расчёт отхода', defaultValue:null, mapFocus:'position', nodes:'move', aliases:['retreatPosition'] }),
  value({ key:'best_cover_position', label:'Best safe position', ru:'Лучшая безопасная позиция', description:'Best awareness point with physical cover as fallback.', descriptionRu:'Лучшая точка личной карты с физическим укрытием как запасным вариантом.', type:'position', category:'cover', source:'Awareness and cover search', sourceRu:'Личная карта и поиск укрытий', defaultValue:null, mapFocus:'cover', nodes:'move', aliases:['bestCoverPosition'] }),
  value({ key:'current_target', label:'Current target', ru:'Текущая цель', description:'Current directly visible threat position.', descriptionRu:'Текущая позиция прямо видимой угрозы.', type:'position', category:'perception', readiness:'simplified', limitation:'Represents a threat-zone position, not a full target object.', limitationRu:'Представляет позицию зоны угрозы, а не полноценный объект цели.', source:'ThreatEvaluation', sourceRu:'Текущая видимая угроза', defaultValue:null, mapFocus:'threat', aliases:['currentTarget'] }),
  value({ key:'remembered_enemy_position', label:'Remembered enemy position', ru:'Запомненная позиция врага', description:'Known threat position used when direct visibility is absent.', descriptionRu:'Известная позиция угрозы при отсутствии прямой видимости.', type:'position', category:'memory', readiness:'simplified', limitation:'Uses the current strongest known threat position.', limitationRu:'Использует позицию текущей самой сильной известной угрозы.', source:'Threat knowledge', sourceRu:'Знания бойца об угрозе', defaultValue:null, mapFocus:'memory', aliases:['rememberedEnemyPosition'] }),
  trait('resilience','Resilience','Стойкость','Ability to withstand combat pressure.','Способность выдерживать боевое давление.'),
  trait('caution','Caution','Осторожность','Preference for safer choices.','Склонность предпочитать безопасные решения.'),
  trait('decisiveness','Decisiveness','Решительность','Tendency to commit to a chosen action.','Склонность уверенно продолжать выбранное действие.'),
  trait('discipline','Discipline','Дисциплина','Ability to follow orders under pressure.','Способность выполнять приказы под давлением.'),
  trait('initiative','Initiative','Инициатива','Willingness to act without a direct order.','Готовность действовать без прямого приказа.'),
  trait('tactics','Tactical skill','Тактика','Tactical decision skill.','Навык тактического выбора решений.'),
  trait('weaponSkill','Weapon skill','Владение оружием','Skill with the current weapon.','Навык обращения с оружием.'),
  condition('confusion','Confusion','Растерянность','Current loss of orientation.','Текущая потеря ориентирования.','hidden'),
  condition('attention','Attention','Внимание','Ability to notice relevant events.','Способность замечать важные события.','hidden'),
  condition('view','Vision','Зрение','Current visual capability.','Текущая способность визуально обнаруживать объекты.','hidden'),
  condition('intuition','Intuition','Интуиция','Ability to infer danger from incomplete information.','Способность предполагать опасность по неполным сведениям.','hidden'),
  condition('speed','Physical speed','Физическая подготовка','Current movement capability.','Текущая физическая способность двигаться.','hidden'),
  condition('stealth','Stealth','Скрытность','Current ability to remain concealed.','Текущая способность оставаться незаметным.','hidden'),
  value({ key:'posture', label:'Posture', ru:'Поза', description:'Current body posture.', descriptionRu:'Текущее положение тела.', type:'text', category:'soldier', source:'Behavior runtime', sourceRu:'Текущее состояние бойца', defaultValue:'standing' }),
  value({ key:'behaviorProfile', label:'Behavior profile', ru:'Профиль поведения', description:'Base behavior profile.', descriptionRu:'Базовый профиль поведения бойца.', type:'text', category:'soldier', source:'Unit model', sourceRu:'Постоянные настройки бойца', defaultValue:'regular' }),
];
