import { actionNode, tacticalCheck, type AiConceptDefinition, type AiConceptMapFocus, type AiConceptReadiness } from './AiConceptTypes';

type OperationArgs = { key:string; kind:'check'|'action'; label:string; ru:string; description:string; descriptionRu:string; readiness?:AiConceptReadiness; limitation?:string; limitationRu?:string; source:string; sourceRu:string; mapFocus?:AiConceptMapFocus; nodeLabel?:string; nodeLabelRu?:string; targetKey?:string };
function operation(a:OperationArgs):AiConceptDefinition {
  const readiness=a.readiness??'ready';
  return { key:a.key, kind:a.kind, category:a.kind==='check'?'tactical':'action', label:a.label, labelRu:a.ru, description:a.description, descriptionRu:a.descriptionRu, readiness,
    readinessExplanation:a.limitation??'Connected for the current simulation scope.', readinessExplanationRu:a.limitationRu??'Подключено для текущего масштаба симуляции.',
    source:a.source, sourceRu:a.sourceRu, mapFocus:a.mapFocus??'unit',
    nodeTemplates:[a.kind==='check'?tacticalCheck(a.key,a.nodeLabel??`Check ${a.key}`,a.nodeLabelRu??`Проверить «${a.ru}»`):actionNode(a.key,a.ru,a.targetKey)],
  };
}

export const AI_OPERATION_CONCEPTS:readonly AiConceptDefinition[]=[
  operation({key:'line_of_sight',kind:'check',label:'Line of sight',ru:'Линия видимости',description:'Checks direct visibility to the threat.',descriptionRu:'Проверяет прямую видимость угрозы.',readiness:'simplified',limitation:'Currently follows enemyVisible.',limitationRu:'Сейчас повторяет значение «Враг виден».',source:'Tactical check',sourceRu:'Текущая видимость угрозы',mapFocus:'threat'}),
  operation({key:'line_of_fire',kind:'check',label:'Line of fire',ru:'Линия огня',description:'Checks whether firing is possible.',descriptionRu:'Проверяет возможность ведения огня.',readiness:'simplified',limitation:'Currently follows enemyVisible and has no ballistic obstruction test.',limitationRu:'Сейчас повторяет «Враг виден» и не имеет полной баллистической проверки.',source:'Tactical check',sourceRu:'Упрощённая проверка огня',mapFocus:'threat'}),
  operation({key:'path_exists',kind:'check',label:'Path exists',ru:'Есть путь',description:'Checks whether a route exists.',descriptionRu:'Проверяет наличие маршрута.',readiness:'planned',limitation:'Currently always returns true.',limitationRu:'Сейчас всегда возвращает «Да».',source:'Tactical placeholder',sourceRu:'Заготовка проверки пути',mapFocus:'route'}),
  operation({key:'cover_exists',kind:'check',label:'Cover exists',ru:'Есть укрытие',description:'Checks whether a cover candidate can be found.',descriptionRu:'Проверяет, удаётся ли найти укрытие.',source:'Tactical check',sourceRu:'Поиск укрытий',mapFocus:'cover'}),
  operation({key:'ammo_available',kind:'check',label:'Ammo available',ru:'Есть боеприпасы',description:'Checks whether ammunition is above zero.',descriptionRu:'Проверяет, больше ли количество патронов нуля.',source:'Tactical check',sourceRu:'Текущее состояние оружия'}),
  operation({key:'can_execute_order',kind:'check',label:'Can execute order',ru:'Можно выполнить приказ',description:'Checks whether a current order exists.',descriptionRu:'Проверяет наличие текущего приказа.',readiness:'simplified',limitation:'Checks order presence, not path or physical capability.',limitationRu:'Проверяет только наличие приказа, а не путь и физическую возможность.',source:'Tactical check',sourceRu:'Текущий приказ',mapFocus:'route'}),
  operation({key:'fire',kind:'action',label:'Fire',ru:'Стрелять',description:'Selects the fire action.',descriptionRu:'Выбирает действие стрельбы.',readiness:'simplified',limitation:'Consumes one round but has no full ballistics or damage.',limitationRu:'Расходует один патрон, но не имеет полной баллистики и повреждений.',source:'Graph effect',sourceRu:'Действие графа',mapFocus:'threat'}),
  operation({key:'reload',kind:'action',label:'Reload',ru:'Перезарядиться',description:'Selects the reload action.',descriptionRu:'Выбирает действие перезарядки.',readiness:'simplified',limitation:'Immediately restores a fixed magazine.',limitationRu:'Сейчас мгновенно восстанавливает фиксированный магазин.',source:'Graph effect',sourceRu:'Действие графа'}),
  operation({key:'retreat',kind:'action',label:'Retreat',ru:'Отступить',description:'Moves toward retreat_position.',descriptionRu:'Создаёт движение к точке отхода.',readiness:'simplified',limitation:'Uses a simple retreat point and ordinary movement.',limitationRu:'Использует простую точку отхода и обычное движение.',source:'Graph effect',sourceRu:'Действие графа',mapFocus:'route',targetKey:'retreat_position'}),
  operation({key:'suppress',kind:'action',label:'Suppress',ru:'Подавлять',description:'Selects suppressive fire.',descriptionRu:'Выбирает подавляющий огонь.',readiness:'simplified',limitation:'Consumes ammunition without complete target-side suppression propagation.',limitationRu:'Расходует патроны без полноценной передачи подавления цели.',source:'Graph effect',sourceRu:'Действие графа',mapFocus:'threat'}),
  operation({key:'wait',kind:'action',label:'Wait',ru:'Ждать',description:'Clears the current order and waits.',descriptionRu:'Очищает текущий приказ и ждёт.',source:'Graph effect',sourceRu:'Действие графа'}),
  operation({key:'continue_order',kind:'action',label:'Continue order',ru:'Продолжать приказ',description:'Keeps the current order as selected behavior.',descriptionRu:'Сохраняет текущий приказ как выбранное поведение.',readiness:'simplified',limitation:'Records the action while the existing order continues.',limitationRu:'Записывает действие, пока существующий приказ продолжается.',source:'Graph effect',sourceRu:'Действие графа',mapFocus:'route'}),
];
