import { AI_CONCEPT_CATALOG, formatAiConceptValue, getAiConcept, validateAiBlackboardSnapshot, type AiConceptCategory, type AiConceptDefinition, type AiConceptNodeTemplate, type AiConceptReadiness } from '../core/ai/AiConceptCatalog';
import type { AiBlackboardValue } from '../core/ai/AiBlackboard';

export const DEFAULT_AI_DICTIONARY_LANGUAGE='ru' as const;
const LANGUAGE_KEY='real-wargame.ai-dictionary.language.v1';
type Language='ru'|'en';
type Filter='all'|string;

export interface AiDictionarySnapshot { readonly unitId:string|null; readonly unitLabel:string; readonly values:Readonly<Record<string,AiBlackboardValue>>; readonly updatedAtMs:number; }
export interface AiDictionaryPanelOptions { readonly mode:'game'|'editor'; readonly getSnapshot:()=>AiDictionarySnapshot; readonly onAddNode?:(concept:AiConceptDefinition,template:AiConceptNodeTemplate)=>void; readonly onShowOnMap?:(concept:AiConceptDefinition,value:AiBlackboardValue|undefined)=>string|void; }
export interface AiDictionaryPanelHandle { readonly open:(conceptKey?:string)=>void; readonly close:()=>void; readonly refresh:()=>void; readonly destroy:()=>void; }

const CATEGORY_ORDER:readonly AiConceptCategory[]=['danger','perception','cover','route','condition','order','memory','decision','tactical','action','soldier'];
const CATEGORY_LABELS:Record<AiConceptCategory,{en:string;ru:string}>={soldier:{en:'Soldier',ru:'Боец'},condition:{en:'Condition',ru:'Состояние'},danger:{en:'Danger and fire',ru:'Опасность и огонь'},perception:{en:'Enemy perception',ru:'Восприятие врага'},cover:{en:'Cover and safety',ru:'Укрытия и безопасность'},route:{en:'Route',ru:'Маршрут'},order:{en:'Orders',ru:'Приказы'},memory:{en:'Memory',ru:'Память'},decision:{en:'Decision',ru:'Решение'},tactical:{en:'Tactical checks',ru:'Тактические проверки'},action:{en:'Actions',ru:'Действия'}};
const READINESS:Record<AiConceptReadiness,{en:string;ru:string;icon:string}>={ready:{en:'Works',ru:'Работает',icon:'●'},simplified:{en:'Simplified',ru:'Упрощённо',icon:'◐'},hidden:{en:'Working, newly exposed',ru:'Работает, раньше было скрыто',icon:'◆'},planned:{en:'Planned',ru:'Заготовка',icon:'○'},deprecated:{en:'Deprecated',ru:'Устарело',icon:'×'},debug:{en:'Debug',ru:'Служебное',icon:'◇'}};

export function installAiDictionaryPanel(options:AiDictionaryPanelOptions):AiDictionaryPanelHandle {
  let language=readLanguage(); let readiness:Filter='all'; let kind:Filter='all'; let category:Filter='all'; let search=''; let selectedKey=AI_CONCEPT_CATALOG[0]?.key??''; let timer=0; let snapshot=options.getSnapshot();
  const root=document.createElement('section'); root.className='ai-dictionary-root'; root.hidden=true; root.setAttribute('aria-label','AI Dictionary');
  root.innerHTML=`<div class="ai-dictionary-backdrop" data-close></div><div class="ai-dictionary-dialog" role="dialog" aria-modal="true"><header class="ai-dictionary-header"><div><span data-kicker></span><h2 data-title></h2><p data-unit></p></div><div><button data-language></button><button data-close aria-label="Close">×</button></div></header><div class="ai-dictionary-toolbar"><label><span data-search-label></span><input type="search" data-ai-dictionary-search></label><label><span data-readiness-label></span><select data-ai-dictionary-readiness></select></label><label><span data-kind-label></span><select data-ai-dictionary-kind></select></label></div><nav data-categories></nav><div class="ai-dictionary-layout"><div data-list></div><aside data-detail></aside></div><footer><span data-count></span><span data-validation></span></footer><div data-toast hidden></div></div>`;
  document.body.append(root);
  const get=<T extends Element>(selector:string):T=>{const found=root.querySelector<T>(selector);if(!found)throw new Error(`AI dictionary element missing: ${selector}`);return found;};
  const searchInput=get<HTMLInputElement>('[data-ai-dictionary-search]'); const readinessSelect=get<HTMLSelectElement>('[data-ai-dictionary-readiness]'); const kindSelect=get<HTMLSelectElement>('[data-ai-dictionary-kind]'); const list=get<HTMLElement>('[data-list]'); const detail=get<HTMLElement>('[data-detail]'); const categories=get<HTMLElement>('[data-categories]');

  root.querySelectorAll<HTMLElement>('[data-close]').forEach((item)=>item.addEventListener('click',close));
  get<HTMLButtonElement>('[data-language]').addEventListener('click',()=>{language=language==='ru'?'en':'ru';localStorage.setItem(LANGUAGE_KEY,language);renderAll();});
  searchInput.addEventListener('input',()=>{search=searchInput.value.trim().toLocaleLowerCase();renderList();renderDetail();});
  readinessSelect.addEventListener('change',()=>{readiness=readinessSelect.value;renderList();renderDetail();});
  kindSelect.addEventListener('change',()=>{kind=kindSelect.value;renderList();renderDetail();});
  categories.addEventListener('click',(event)=>{const button=(event.target as Element|null)?.closest<HTMLButtonElement>('[data-category]');if(!button)return;category=button.dataset.category??'all';renderCategories();renderList();renderDetail();});
  list.addEventListener('click',(event)=>{const button=(event.target as Element|null)?.closest<HTMLButtonElement>('[data-ai-dictionary-concept]');if(!button?.dataset.aiDictionaryConcept)return;selectedKey=button.dataset.aiDictionaryConcept;renderList();renderDetail();});
  detail.addEventListener('click',(event)=>{const add=(event.target as Element|null)?.closest<HTMLButtonElement>('[data-ai-dictionary-add-node]');if(add){const concept=getAiConcept(selectedKey);const template=concept?.nodeTemplates[Number(add.dataset.aiDictionaryAddNode)];if(concept&&template&&options.onAddNode)options.onAddNode(concept,template);return;}const map=(event.target as Element|null)?.closest<HTMLButtonElement>('[data-ai-dictionary-show-map]');if(map){const concept=getAiConcept(selectedKey);if(!concept||!options.onShowOnMap)return;showToast(options.onShowOnMap(concept,snapshot.values[concept.key])||t('Map focus activated.','Слой или точка показаны на карте.'));}});
  const keyHandler=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!root.hidden)close();}; window.addEventListener('keydown',keyHandler);
  renderAll();

  function open(conceptKey?:string):void {if(conceptKey&&getAiConcept(conceptKey))selectedKey=conceptKey;root.hidden=false;document.body.classList.add('ai-dictionary-open');snapshot=options.getSnapshot();renderAll();searchInput.focus();window.clearInterval(timer);timer=window.setInterval(refreshLive,500);}
  function close():void {root.hidden=true;document.body.classList.remove('ai-dictionary-open');window.clearInterval(timer);timer=0;}
  function refresh():void {refreshLive();renderDetail();}
  function destroy():void {close();window.removeEventListener('keydown',keyHandler);root.remove();}
  function renderAll():void {snapshot=options.getSnapshot();renderLabels();renderCategories();renderList();renderDetail();}

  function renderLabels():void {
    get('[data-kicker]').textContent=t('Human-facing AI data contract','Понятный человеку внутренний словарь'); get('[data-title]').textContent=t('Soldier AI Dictionary','Словарь ИИ солдата'); get('[data-unit]').textContent=snapshot.unitId?t(`Live soldier: ${snapshot.unitLabel}`,`Живой боец: ${snapshot.unitLabel}`):t('Reference mode: no live soldier selected','Режим справочника: живой боец не выбран'); get<HTMLButtonElement>('[data-language]').textContent=language==='ru'?'EN':'RU';
    get('[data-search-label]').textContent=t('Search','Поиск'); searchInput.placeholder=t('fire, cover, route…','огонь, укрытие, маршрут…'); get('[data-readiness-label]').textContent=t('Readiness','Готовность'); get('[data-kind-label]').textContent=t('Type','Тип');
    readinessSelect.innerHTML=`<option value="all">${t('All readiness states','Все статусы')}</option>${Object.entries(READINESS).map(([key,item])=>`<option value="${key}">${item.icon} ${item[language]}</option>`).join('')}`; readinessSelect.value=readiness;
    const kinds=[['all',t('All types','Все типы')],['value',t('Soldier values','Значения бойца')],['check',t('Tactical checks','Тактические проверки')],['action',t('Actions','Действия')]]; kindSelect.innerHTML=kinds.map(([value,label])=>`<option value="${value}">${label}</option>`).join('');kindSelect.value=kind;
  }
  function renderCategories():void {categories.innerHTML=`<button data-category="all" class="${category==='all'?'active':''}">${t('All','Все')}</button>${CATEGORY_ORDER.map((item)=>`<button data-category="${item}" class="${category===item?'active':''}">${CATEGORY_LABELS[item][language]}</button>`).join('')}`;}
  function filtered():AiConceptDefinition[]{return AI_CONCEPT_CATALOG.filter((concept)=>(readiness==='all'||concept.readiness===readiness)&&(kind==='all'||concept.kind===kind)&&(category==='all'||concept.category===category)&&(!search||[concept.key,concept.label,concept.labelRu,concept.description,concept.descriptionRu,concept.source,concept.sourceRu].join(' ').toLocaleLowerCase().includes(search)));}
  function renderList():void {snapshot=options.getSnapshot();const concepts=filtered();if(!concepts.some((item)=>item.key===selectedKey)&&concepts[0])selectedKey=concepts[0].key;list.className='ai-dictionary-list';list.innerHTML=concepts.length?concepts.map((concept)=>{const status=READINESS[concept.readiness];const value=concept.kind==='value'?formatAiConceptValue(concept,snapshot.values[concept.key],language):t('Open description','Открыть описание');return `<button class="ai-dictionary-card ${selectedKey===concept.key?'selected':''}" data-ai-dictionary-concept="${attr(concept.key)}"><span class="readiness-${concept.readiness}">${status.icon}</span><span><strong>${html(local(concept,'label'))}</strong><small>${html(concept.key)}</small></span><b data-ai-dictionary-live-value="${attr(concept.key)}">${html(value)}</b></button>`;}).join(''):`<p>${t('Nothing found.','Ничего не найдено.')}</p>`;get('[data-count]').textContent=t(`${concepts.length} concepts`,`Понятий: ${concepts.length}`);const report=validateAiBlackboardSnapshot(snapshot.values);get('[data-validation]').textContent=report.valid?t('Dictionary contract is valid.','Проверка словаря пройдена.') : t(`${report.unknownKeys.length} unknown fields, ${report.typeMismatches.length} type errors.`,`Неизвестных полей: ${report.unknownKeys.length}; ошибок типа: ${report.typeMismatches.length}.`);}
  function renderDetail():void {const concept=getAiConcept(selectedKey)??filtered()[0];if(!concept){detail.innerHTML='';return;}const status=READINESS[concept.readiness];const value=concept.kind==='value'?formatAiConceptValue(concept,snapshot.values[concept.key],language):t('Not a live value','Не является живым значением');const add=concept.nodeTemplates.length?concept.nodeTemplates.map((template,index)=>`<button data-ai-dictionary-add-node="${index}" ${options.onAddNode?'':'disabled'}>${html(language==='ru'?template.labelRu:template.label)}</button>`).join(''):`<span>${t('No direct node template.','Нет готового шаблона ноды.')}</span>`;detail.className='ai-dictionary-detail';detail.innerHTML=`<header><span class="readiness-${concept.readiness}">${status.icon} ${status[language]}</span><h3>${html(local(concept,'label'))}</h3><code>${html(concept.key)}</code></header><div class="ai-dictionary-current-value"><span>${t('Current value','Текущее значение')}</span><strong data-ai-dictionary-detail-value>${html(value)}</strong></div><p>${html(local(concept,'description'))}</p><dl><div><dt>${t('Category','Категория')}</dt><dd>${CATEGORY_LABELS[concept.category][language]}</dd></div><div><dt>${t('Source','Источник')}</dt><dd>${html(language==='ru'?concept.sourceRu:concept.source)}</dd></div><div><dt>${t('Readiness','Готовность')}</dt><dd>${html(language==='ru'?concept.readinessExplanationRu:concept.readinessExplanation)}</dd></div><div><dt>${t('Value type','Тип значения')}</dt><dd>${concept.valueType??concept.kind}</dd></div></dl><section class="ai-dictionary-why"><h4>${t('Why this value?','Почему такое значение?')}</h4><p>${html(explain(concept))}</p></section><button data-ai-dictionary-show-map ${options.onShowOnMap&&concept.mapFocus!=='none'?'':'disabled'}>${t('Show on map','Показать на карте')}</button><section class="ai-dictionary-node-actions"><h4>${t('Use in graph','Использовать в графе')}</h4><div>${add}</div></section>`;}
  function refreshLive():void {const next=options.getSnapshot();const unitChanged=next.unitId!==snapshot.unitId||next.unitLabel!==snapshot.unitLabel;snapshot=next;root.querySelectorAll<HTMLElement>('[data-ai-dictionary-live-value]').forEach((element)=>{const concept=getAiConcept(element.dataset.aiDictionaryLiveValue??'');if(concept)element.textContent=concept.kind==='value'?formatAiConceptValue(concept,next.values[concept.key],language):t('Open description','Открыть описание');});if(unitChanged)renderLabels();const concept=getAiConcept(selectedKey);if(concept?.kind==='value'){const value=root.querySelector<HTMLElement>('[data-ai-dictionary-detail-value]');if(value)value.textContent=formatAiConceptValue(concept,next.values[concept.key],language);const why=root.querySelector<HTMLElement>('.ai-dictionary-why p');if(why)why.textContent=explain(concept);}}
  function explain(concept:AiConceptDefinition):string {const values=snapshot.values;if(concept.key==='underFire'){const danger=Number(values.danger??0),suppression=Number(values.suppression??0),result=danger>0||suppression>0;return t(`Rule: danger above 0 or suppression above 0. Current values: ${danger} and ${suppression}; result: ${result?'Yes':'No'}.`,`Условие: опасность больше 0 или подавление больше 0. Сейчас: ${danger} и ${suppression}; результат: ${result?'Да':'Нет'}.`);}if(concept.key==='weaponReady')return t(`Weapon readiness also requires ammunition above zero. Current ammunition: ${Number(values.ammo??0)}.`,`Готовность оружия также требует патроны больше нуля. Сейчас патронов: ${Number(values.ammo??0)}.`);if(concept.key==='isInCover')return t(`The flag is true when protection is above zero. Current protection: ${Number(values.coverProtection??0)}.`,`Флаг включается при защите выше нуля. Текущая защита: ${Number(values.coverProtection??0)}.`);if(concept.key==='routeDanger')return values.routeDanger===null?t('There is no published active-route diagnostic. Current-position danger is not substituted.','Нет опубликованной диагностики активного маршрута. Опасность текущей позиции не подставляется.'):t('Average subjective danger from the canonical diagnostic stored with the active route.','Средняя субъективная опасность из канонической диагностики, сохранённой вместе с активным маршрутом.');const value=values[concept.key];if(concept.kind!=='value')return language==='ru'?concept.readinessExplanationRu:concept.readinessExplanation;if(value===undefined)return t('Select a soldier or run one AI evaluation.','Выберите бойца или выполните один расчёт ИИ.');return t(`Source: ${concept.source}. Current value: ${formatAiConceptValue(concept,value,language)}.`,`Источник: ${concept.sourceRu}. Текущее значение: ${formatAiConceptValue(concept,value,language)}.`);}
  function showToast(message:string):void {const toast=get<HTMLElement>('[data-toast]');toast.textContent=message;toast.hidden=false;window.setTimeout(()=>{toast.hidden=true;},2600);}
  function local(concept:AiConceptDefinition,field:'label'|'description'):string{return field==='label'?(language==='ru'?concept.labelRu:concept.label):(language==='ru'?concept.descriptionRu:concept.description);}
  function t(en:string,ru:string):string{return language==='ru'?ru:en;}
  return {open,close,refresh,destroy};
}
function readLanguage():Language {try{return localStorage.getItem(LANGUAGE_KEY)==='en'?'en':DEFAULT_AI_DICTIONARY_LANGUAGE;}catch{return DEFAULT_AI_DICTIONARY_LANGUAGE;}}
function html(value:string):string{return value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function attr(value:string):string{return html(value);}
