import { BUILT_IN_MOVEMENT_PROFILES, cloneMovementProfile, getBuiltInMovementProfile } from './MovementProfileDefaults';
import { normalizeCustomMovementId, normalizeMovementProfile, normalizeMovementRegistryData } from './MovementProfileNormalization';
import { MOVEMENT_PROFILE_FORMAT_VERSION, type BuiltInMovementProfileId, type MovementProfile, type MovementProfileRegistryData } from './MovementProfileTypes';

export class MovementProfileRegistry{
 readonly formatVersion=MOVEMENT_PROFILE_FORMAT_VERSION;private registryRevision:number;private readonly profiles=new Map<string,MovementProfile>();
 constructor(data?:Partial<MovementProfileRegistryData>){const normalized=normalizeMovementRegistryData(data);this.registryRevision=normalized.revision;for(const p of normalized.profiles)this.profiles.set(p.id,cloneMovementProfile(p));}
 get revision():number{return this.registryRevision;}
 listProfiles():MovementProfile[]{const built=BUILT_IN_MOVEMENT_PROFILES.map(p=>this.profiles.get(p.id)).filter((p):p is MovementProfile=>Boolean(p));const custom=[...this.profiles.values()].filter(p=>!p.builtIn).sort((a,b)=>a.sortOrder-b.sortOrder||a.nameRu.localeCompare(b.nameRu)||a.id.localeCompare(b.id));return [...built,...custom].map(cloneMovementProfile);}
 hasProfile(id:string):boolean{return this.profiles.has(id);}
 getProfile(id:string):MovementProfile{const value=this.profiles.get(id)??this.profiles.get('normal_walk');if(!value)throw new Error('Movement profile registry is missing normal_walk.');return cloneMovementProfile(value);}
 createCustomProfile(id:string,nameEn:string,nameRu:string,sourceId='normal_walk'):MovementProfile{const normalizedId=normalizeCustomMovementId(id);if(this.profiles.has(normalizedId))throw new Error(`Movement profile already exists: ${normalizedId}`);const source=this.getProfile(sourceId),created=normalizeMovementProfile({...source,id:normalizedId,nameEn:clean(nameEn,normalizedId),nameRu:clean(nameRu,nameEn||normalizedId),descriptionEn:`Custom profile based on ${source.nameEn}.`,descriptionRu:`Пользовательский профиль на основе «${source.nameRu}».`,templateProfileId:source.templateProfileId,fallbackProfileId:source.fallbackProfileId===source.id?null:source.fallbackProfileId,sortOrder:this.nextSortOrder(),revision:1,builtIn:false});this.profiles.set(created.id,created);this.touch();return this.getProfile(created.id);}
 copyProfile(sourceId:string,id:string,nameEn:string,nameRu:string):MovementProfile{return this.createCustomProfile(id,nameEn,nameRu,sourceId);}
 updateProfile(id:string,changes:Partial<Omit<MovementProfile,'id'|'builtIn'|'revision'>>):MovementProfile{const current=this.require(id),updated=normalizeMovementProfile({...current,...clone(changes),id:current.id,builtIn:current.builtIn,revision:current.revision+1});this.profiles.set(id,updated);this.touch();return cloneMovementProfile(updated);}
 renameProfile(id:string,nameEn:string,nameRu:string):MovementProfile{return this.updateProfile(id,{nameEn:clean(nameEn,id),nameRu:clean(nameRu,nameEn||id)});}
 deleteProfile(id:string):boolean{const current=this.profiles.get(id);if(!current||current.builtIn)return false;this.profiles.delete(id);for(const p of this.profiles.values())if(p.fallbackProfileId===id){p.fallbackProfileId=p.templateProfileId===p.id?null:p.templateProfileId;p.revision+=1;}this.touch();return true;}
 resetProfile(id:string):MovementProfile{const current=this.require(id),defaults=getBuiltInMovementProfile(current.builtIn?id as BuiltInMovementProfileId:current.templateProfileId);this.profiles.set(id,current.builtIn?{...defaults,revision:current.revision+1}:{...defaults,id:current.id,nameEn:current.nameEn,nameRu:current.nameRu,descriptionEn:current.descriptionEn,descriptionRu:current.descriptionRu,sortOrder:current.sortOrder,revision:current.revision+1,builtIn:false});this.touch();return this.getProfile(id);}
 toData():MovementProfileRegistryData{return {formatVersion:MOVEMENT_PROFILE_FORMAT_VERSION,revision:this.registryRevision,profiles:this.listProfiles()};}
 exportJson():string{return `${JSON.stringify(this.toData(),null,2)}\n`;}
 static fromUnknown(value:unknown):MovementProfileRegistry{if(!record(value))throw new Error('Movement profile import must be a JSON object.');if('profiles'in value&&!Array.isArray(value.profiles))throw new Error('Movement profile import field "profiles" must be an array.');return new MovementProfileRegistry(value as Partial<MovementProfileRegistryData>);}
 static importJson(raw:string):MovementProfileRegistry{let value:unknown;try{value=JSON.parse(raw);}catch{throw new Error('Movement profile import is not valid JSON.');}return this.fromUnknown(value);}
 private require(id:string):MovementProfile{const value=this.profiles.get(id);if(!value)throw new Error(`Unknown movement profile: ${id}`);return cloneMovementProfile(value);}private touch():void{this.registryRevision+=1;}private nextSortOrder():number{return Math.max(100,...[...this.profiles.values()].map(p=>p.sortOrder))+10;}
}
export function createDefaultMovementProfileRegistry():MovementProfileRegistry{return new MovementProfileRegistry();}
function clean(value:unknown,fallback:unknown):string{const v=typeof value==='string'?value.trim():'';const f=typeof fallback==='string'?fallback.trim():'';return v||f||'Movement profile';}function clone<T>(value:T):T{return typeof structuredClone==='function'?structuredClone(value):JSON.parse(JSON.stringify(value)) as T;}function record(value:unknown):value is Record<string,unknown>{return typeof value==='object'&&value!==null&&!Array.isArray(value);}
