import { SOLDIER_BLACKBOARD_SCHEMA, type AiBlackboardDefaults, type AiBlackboardSchemaEntry, type AiBlackboardValue } from '../AiBlackboard';
import type { AiGraphV2, AiNodeParameters, AiNodeV2 } from '../AiGraph';
import { createContractDefaultParameters } from './AiNodeContractRegistry';
export interface AiGraphMigrationIssue {readonly severity:'error'|'warning'|'info';readonly code:string;readonly message:string;readonly messageRu:string;readonly nodeId?:string;readonly parameterName?:string;readonly fixRu?:string;}
export type AiGraphMigrationResult=|{readonly ok:true;readonly migrated:boolean;readonly graph:AiGraphV2;readonly issues:readonly AiGraphMigrationIssue[]}|{readonly ok:false;readonly migrated:false;readonly original:unknown;readonly issues:readonly AiGraphMigrationIssue[]};
const GRAPH_FIELDS=new Set(['version','id','name','nameRu','description','descriptionRu','rootNodeId','blackboardSchema','blackboardDefaults','nodes','subgraphRefs','legacyMetadata']);
const NODE_FIELDS=new Set(['id','type','displayName','displayNameRu','description','descriptionRu','children','parameters','inputBindings','outputBindings','legacyMetadata']);
export function migrateAiGraphToV2(value:unknown):AiGraphMigrationResult{
 if(!isRecord(value))return failed(value,'GRAPH_NOT_OBJECT','AI graph must be an object.','AI-граф должен быть объектом.');
 if(value.version===2){const graph=normalizeV2(value);return graph?{ok:true,migrated:false,graph,issues:[]}:failed(value,'GRAPH_V2_MALFORMED','Graph v2 is malformed.','Graph v2 имеет повреждённую структуру.');}
 if(value.version!==1)return failed(value,'UNSUPPORTED_GRAPH_VERSION','Only graph v1 or v2 can be loaded.','Можно загрузить только graph v1 или v2.');
 const issues:AiGraphMigrationIssue[]=[];if(!isNonEmptyString(value.id))issues.push(err('MISSING_GRAPH_ID','Graph id is missing.','У графа отсутствует id.'));if(!isNonEmptyString(value.rootNodeId))issues.push(err('MISSING_ROOT_NODE_ID','Root id missing.','У графа отсутствует rootNodeId.'));if(!Array.isArray(value.nodes))issues.push(err('NODES_NOT_ARRAY','Nodes must be array.','Ноды должны быть массивом.'));if(!isRecord(value.blackboardDefaults))issues.push(err('BLACKBOARD_DEFAULTS_NOT_OBJECT','Defaults must be object.','Blackboard defaults должны быть объектом.'));if(issues.length)return{ok:false,migrated:false,original:value,issues};
 const nodes:AiNodeV2[]=[];for(const [index,raw] of (value.nodes as unknown[]).entries()){if(!isRecord(raw)||!isNonEmptyString(raw.id)||!isNonEmptyString(raw.type)){issues.push(err('NODE_MIGRATION_FAILED',`Node #${index+1} cannot be migrated.`,`Ноду #${index+1} невозможно перенести.`));continue;}const legacy=merge(isRecord(raw.legacyMetadata)?raw.legacyMetadata:undefined,unknownFields(raw,NODE_FIELDS));const parameters=normalizeParameters(raw.parameters,raw.type,raw.id,issues);if(!parameters)continue;const inputBindings=isRecord(raw.inputBindings)?clone(raw.inputBindings) as AiNodeV2['inputBindings']:raw.type==='MoveToBlackboardPosition'&&typeof parameters.targetKey==='string'?{target:{source:'blackboard' as const,key:parameters.targetKey}}:undefined;nodes.push({id:raw.id,type:raw.type,displayName:str(raw.displayName),displayNameRu:str(raw.displayNameRu),description:str(raw.description),descriptionRu:str(raw.descriptionRu),children:Array.isArray(raw.children)?raw.children.filter(isNonEmptyString):[],parameters,inputBindings,outputBindings:isRecord(raw.outputBindings)?clone(raw.outputBindings) as AiNodeV2['outputBindings']:undefined,legacyMetadata:Object.keys(legacy).length?legacy:undefined});}
 if(issues.some(x=>x.severity==='error'))return{ok:false,migrated:false,original:value,issues};const defaults=blackboardDefaults(value.blackboardDefaults as Record<string,unknown>);if(!defaults)return failed(value,'BLACKBOARD_VALUE_UNSUPPORTED','Unsupported Blackboard value.','Неподдерживаемое значение Blackboard.');const legacy=merge(isRecord(value.legacyMetadata)?value.legacyMetadata:undefined,unknownFields(value,GRAPH_FIELDS));const refs=unique(nodes.filter(n=>n.type==='Subgraph').map(n=>n.parameters?.subgraphId).filter(isNonEmptyString));return{ok:true,migrated:true,graph:{version:2,id:value.id as string,name:isNonEmptyString(value.name)?value.name:value.id as string,nameRu:str(value.nameRu),description:str(value.description),descriptionRu:str(value.descriptionRu),rootNodeId:value.rootNodeId as string,blackboardSchema:buildSchema(defaults),blackboardDefaults:defaults,nodes,subgraphRefs:refs,legacyMetadata:Object.keys(legacy).length?legacy:undefined},issues:[...issues,{severity:'info',code:'GRAPH_V1_MIGRATED',message:'Graph v1 migrated in memory.',messageRu:'Graph v1 преобразован в graph v2 в памяти.'}]};
}
function normalizeV2(v:Record<string,unknown>):AiGraphV2|undefined{if(!isNonEmptyString(v.id)||!isNonEmptyString(v.rootNodeId)||!Array.isArray(v.nodes)||!isRecord(v.blackboardDefaults)||!Array.isArray(v.blackboardSchema)||!Array.isArray(v.subgraphRefs))return;const nodes:AiNodeV2[]=[];for(const raw of v.nodes){if(!isRecord(raw)||!isNonEmptyString(raw.id)||!isNonEmptyString(raw.type))return;const p=normalizeParameters(raw.parameters,raw.type,raw.id,[]);if(!p)return;nodes.push({id:raw.id,type:raw.type,displayName:str(raw.displayName),displayNameRu:str(raw.displayNameRu),description:str(raw.description),descriptionRu:str(raw.descriptionRu),children:Array.isArray(raw.children)?raw.children.filter(isNonEmptyString):[],parameters:p,inputBindings:isRecord(raw.inputBindings)?clone(raw.inputBindings) as AiNodeV2['inputBindings']:undefined,outputBindings:isRecord(raw.outputBindings)?clone(raw.outputBindings) as AiNodeV2['outputBindings']:undefined,legacyMetadata:isRecord(raw.legacyMetadata)?clone(raw.legacyMetadata):undefined});}const defaults=blackboardDefaults(v.blackboardDefaults);if(!defaults)return;return{version:2,id:v.id,name:isNonEmptyString(v.name)?v.name:v.id,nameRu:str(v.nameRu),description:str(v.description),descriptionRu:str(v.descriptionRu),rootNodeId:v.rootNodeId,blackboardSchema:clone(v.blackboardSchema) as unknown as readonly AiBlackboardSchemaEntry[],blackboardDefaults:defaults,nodes,subgraphRefs:unique(v.subgraphRefs.filter(isNonEmptyString)),legacyMetadata:isRecord(v.legacyMetadata)?clone(v.legacyMetadata):undefined};}
function normalizeParameters(v:unknown,type:string,nodeId:string,issues:AiGraphMigrationIssue[]):AiNodeParameters|undefined{if(v!==undefined&&!isRecord(v)){issues.push(err('PARAMETERS_NOT_OBJECT',`Node ${nodeId} parameters invalid.`,`Параметры ноды ${nodeId} неверны.`,nodeId));return;}const r:AiNodeParameters={...createContractDefaultParameters(type)};for(const[k,x]of Object.entries((v??{}) as Record<string,unknown>)){if(!isValue(x)){issues.push(err('PARAMETER_VALUE_UNSUPPORTED',`Parameter ${k} cannot migrate.`,`Параметр ${k} невозможно перенести.`,nodeId,k));continue;}r[k]=cloneValue(x);}return issues.some(x=>x.severity==='error'&&x.nodeId===nodeId)?undefined:r;}
function buildSchema(defaults:AiBlackboardDefaults):AiBlackboardSchemaEntry[]{const known=new Map<string,AiBlackboardSchemaEntry>(SOLDIER_BLACKBOARD_SCHEMA.map(x=>[x.key,x]));return Object.entries(defaults).map(([key,v])=>{const e=known.get(key);if(e)return{...e,defaultValue:cloneValue(v)};const valueKind=v===null?'string':typeof v==='number'?'number':typeof v==='boolean'?'boolean':typeof v==='object'?'position':'string';return{key,valueKind,label:key,description:`Migrated key ${key}.`,labelRu:key,descriptionRu:`Перенесённый ключ ${key}.`,defaultValue:cloneValue(v)} as AiBlackboardSchemaEntry;});}
function blackboardDefaults(v:Record<string,unknown>):AiBlackboardDefaults|undefined{const r:AiBlackboardDefaults={};for(const[k,x]of Object.entries(v)){if(!isValue(x))return;r[k]=cloneValue(x);}return r;}function unknownFields(v:Record<string,unknown>,known:Set<string>):Record<string,unknown>{const r:Record<string,unknown>={};for(const[k,x]of Object.entries(v))if(!known.has(k))r[k]=clone(x);return r;}function merge(...values:(Record<string,unknown>|undefined)[]):Record<string,unknown>{return Object.assign({},...values.filter(Boolean).map(x=>clone(x!)));}
function cloneValue(v:AiBlackboardValue):AiBlackboardValue{return typeof v==='object'&&v!==null?{x:v.x,y:v.y}:v;}function isValue(v:unknown):v is AiBlackboardValue{return v===null||typeof v==='string'||typeof v==='boolean'||(typeof v==='number'&&Number.isFinite(v))||(isRecord(v)&&typeof v.x==='number'&&Number.isFinite(v.x)&&typeof v.y==='number'&&Number.isFinite(v.y));}
function clone<T>(v:T):T{if(Array.isArray(v))return v.map(clone) as T;if(isRecord(v)){const r:Record<string,unknown>={};for(const[k,x]of Object.entries(v))r[k]=clone(x);return r as T;}return v;}function unique(v:readonly string[]):string[]{return[...new Set(v)];}function str(v:unknown):string|undefined{return typeof v==='string'?v:undefined;}function isNonEmptyString(v:unknown):v is string{return typeof v==='string'&&v.trim().length>0;}function isRecord(v:unknown):v is Record<string,unknown>{return typeof v==='object'&&v!==null&&!Array.isArray(v);}function err(code:string,message:string,messageRu:string,nodeId?:string,parameterName?:string):AiGraphMigrationIssue{return{severity:'error',code,message,messageRu,nodeId,parameterName};}function failed(original:unknown,code:string,message:string,messageRu:string):AiGraphMigrationResult{return{ok:false,migrated:false,original,issues:[err(code,message,messageRu)]};}
