import type { AiBlackboardValue } from '../AiBlackboard';
export type AiMemoryScopeName='persistentSoldierMemory'|'runtimeSessionMemory'|'activeStateMemory'|'subgraphLocalMemory'|'nodeLocalState';
export type AiMemoryRecord=Readonly<Record<string,AiBlackboardValue>>;
export interface AiMemoryScopesSnapshotV1 {readonly version:1;readonly persistentSoldierMemory:AiMemoryRecord;readonly runtimeSessionMemory:AiMemoryRecord;readonly activeStateMemory:AiMemoryRecord;readonly subgraphLocalMemory:Readonly<Record<string,AiMemoryRecord>>;readonly nodeLocalState:Readonly<Record<string,AiMemoryRecord>>;}
export interface CreateAiMemoryScopesInput {readonly persistentSoldierMemory?:AiMemoryRecord;readonly runtimeSessionMemory?:AiMemoryRecord;readonly activeStateMemory?:AiMemoryRecord;readonly subgraphLocalMemory?:Readonly<Record<string,AiMemoryRecord>>;readonly nodeLocalState?:Readonly<Record<string,AiMemoryRecord>>;}
export function createAiMemoryScopes(input:CreateAiMemoryScopesInput={}):AiMemoryScopesSnapshotV1{return{version:1,persistentSoldierMemory:cloneMemory(input.persistentSoldierMemory),runtimeSessionMemory:cloneMemory(input.runtimeSessionMemory),activeStateMemory:cloneMemory(input.activeStateMemory),subgraphLocalMemory:cloneNested(input.subgraphLocalMemory),nodeLocalState:cloneNested(input.nodeLocalState)};}
export function normalizeAiMemoryScopes(value:unknown,legacy:AiMemoryRecord={}):AiMemoryScopesSnapshotV1{if(!isRecord(value)||value.version!==1)return createAiMemoryScopes({runtimeSessionMemory:legacy});return createAiMemoryScopes({persistentSoldierMemory:normalizeMemory(value.persistentSoldierMemory),runtimeSessionMemory:normalizeMemory(value.runtimeSessionMemory),activeStateMemory:normalizeMemory(value.activeStateMemory),subgraphLocalMemory:normalizeNested(value.subgraphLocalMemory),nodeLocalState:normalizeNested(value.nodeLocalState)});}
export function cloneAiMemoryScopes(v:AiMemoryScopesSnapshotV1):AiMemoryScopesSnapshotV1{return createAiMemoryScopes(v);}
export function readAiMemoryValue(s:AiMemoryScopesSnapshotV1,scope:AiMemoryScopeName,key:string,ownerId?:string):AiBlackboardValue|undefined{const v=scope==='subgraphLocalMemory'?(ownerId?s.subgraphLocalMemory[ownerId]?.[key]:undefined):scope==='nodeLocalState'?(ownerId?s.nodeLocalState[ownerId]?.[key]:undefined):s[scope][key];return v===undefined?undefined:cloneValue(v);}
export function writeAiMemoryValue(s:AiMemoryScopesSnapshotV1,scope:AiMemoryScopeName,ownerOrKey:string,keyOrValue:string|AiBlackboardValue,maybeValue?:AiBlackboardValue):AiMemoryScopesSnapshotV1{if(scope==='subgraphLocalMemory'||scope==='nodeLocalState'){if(maybeValue===undefined)throw new Error(`${scope} write requires ownerId, key and value.`);const nested=cloneNested(s[scope]);nested[ownerOrKey]={...(nested[ownerOrKey]??{}),[String(keyOrValue)]:cloneValue(maybeValue)};return{...cloneAiMemoryScopes(s),[scope]:nested};}return{...cloneAiMemoryScopes(s),[scope]:{...s[scope],[ownerOrKey]:cloneValue(keyOrValue as AiBlackboardValue)}};}
export function resetAiMemoryScope(s:AiMemoryScopesSnapshotV1,scope:AiMemoryScopeName,ownerId?:string):AiMemoryScopesSnapshotV1{const next=cloneAiMemoryScopes(s);if(scope==='subgraphLocalMemory'||scope==='nodeLocalState'){if(!ownerId)return{...next,[scope]:{}};const nested=cloneNested(next[scope]);delete nested[ownerId];return{...next,[scope]:nested};}return{...next,[scope]:{}};}
export const AI_MEMORY_SCOPE_LABELS_RU:Readonly<Record<AiMemoryScopeName,string>>={persistentSoldierMemory:'Постоянная память бойца',runtimeSessionMemory:'Память runtime session',activeStateMemory:'Память активного состояния',subgraphLocalMemory:'Локальная память подграфа',nodeLocalState:'Локальное состояние ноды'};
function normalizeMemory(value:unknown):AiMemoryRecord{if(!isRecord(value))return{};const r:Record<string,AiBlackboardValue>={};for(const[k,v]of Object.entries(value))if(isValue(v))r[k]=cloneValue(v);return r;}
function normalizeNested(value:unknown):Readonly<Record<string,AiMemoryRecord>>{if(!isRecord(value))return{};const r:Record<string,AiMemoryRecord>={};for(const[k,v]of Object.entries(value))r[k]=normalizeMemory(v);return r;}
function cloneMemory(v:AiMemoryRecord|undefined):Record<string,AiBlackboardValue>{const r:Record<string,AiBlackboardValue>={};for(const[k,x]of Object.entries(v??{}))r[k]=cloneValue(x);return r;}
function cloneNested(v:Readonly<Record<string,AiMemoryRecord>>|undefined):Record<string,AiMemoryRecord>{const r:Record<string,AiMemoryRecord>={};for(const[k,x]of Object.entries(v??{}))r[k]=cloneMemory(x);return r;}
function cloneValue(v:AiBlackboardValue):AiBlackboardValue{return typeof v==='object'&&v!==null?{x:v.x,y:v.y}:v;}
function isValue(v:unknown):v is AiBlackboardValue{return v===null||typeof v==='string'||typeof v==='boolean'||(typeof v==='number'&&Number.isFinite(v))||(isRecord(v)&&typeof v.x==='number'&&typeof v.y==='number');}
function isRecord(v:unknown):v is Record<string,unknown>{return typeof v==='object'&&v!==null&&!Array.isArray(v);}
