import { getBuiltInMovementProfile, type MovementGait, type MovementProfile, type MovementProfileRegistry } from '../core/movement/MovementProfiles';
import { MOVEMENT_EDITOR_GROUPS, type MovementEditorField, type MovementEditorGroup } from './MovementProfileEditorSchema';

export function renderMovementProfileEditorView(registry: MovementProfileRegistry, draft: MovementProfile, selectedId: string, dirty: boolean): string {
  return `<div class="navigation-profile-layout movement-profile-editor-layout">
  <aside class="navigation-profile-list-panel"><div class="navigation-profile-list-heading"><div><h2>Профили движения</h2><p>Как боец физически идёт, бежит и ползёт.</p></div><span>Формат v${registry.formatVersion}</span></div>
  <div class="navigation-profile-list">${registry.listProfiles().map(p=>profileButton(p,selectedId)).join('')}</div><div class="navigation-profile-list-actions">${button('create','Создать профиль')}${button('copy','Копировать')}${button('rename','Переименовать')}${button('delete','Удалить',draft.builtIn)}${button('reset','Сбросить')}${button('import','Импорт')}${button('export','Экспорт')}<input type="file" data-movement-import accept="application/json,.json" hidden/></div></aside>
  <main class="navigation-profile-form-panel"><header class="navigation-profile-form-heading"><div><span class="navigation-profile-kicker">${draft.builtIn?'Встроенный':'Пользовательский'} · версия ${draft.revision}</span><h2>${esc(draft.nameRu)}</h2><p>${esc(draft.descriptionRu)}</p></div><div class="navigation-profile-form-actions">${button('cancel','Отменить изменения',!dirty)}${button('save','Сохранить изменения',!dirty,'primary')}</div></header>
  <div class="movement-profile-status" data-movement-status aria-live="polite">${dirty?'Есть несохранённые изменения.':'Изменения сохранены.'}</div>
  <section class="navigation-profile-name-card">${text('nameRu','Название по-русски',draft.nameRu)}${text('nameEn','Название по-английски',draft.nameEn)}${area('descriptionRu','Описание по-русски',draft.descriptionRu)}${area('descriptionEn','Описание по-английски',draft.descriptionEn)}</section>
  <section class="navigation-profile-group"><h3>Основное</h3><p class="movement-profile-group-description">Технический идентификатор создаётся автоматически. Профиль, фактический способ движения и текущее состояние бойца разделены.</p><div class="movement-profile-select-grid">${select('preferredGait','Предпочитаемый способ движения',[['walk','Шаг'],['crouch_walk','Пригнувшись'],['run','Бег'],['sprint','Спринт'],['crawl','Ползком']],draft.preferredGait)}${select('stancePolicy','Политика позы',[['standing','Стоя'],['crouched','Пригнувшись'],['prone','Лёжа'],['adaptive','Адаптивно']],draft.stancePolicy)}${fallbackSelect(registry,draft)}${select('category','Категория',[['routine','Обычное'],['stealth','Скрытное'],['combat','Боевое'],['emergency','Экстренное']],draft.category)}${numberInput('sortOrder','Порядок в списке',draft.sortOrder,0,100000,1)}</div></section>
  ${MOVEMENT_EDITOR_GROUPS.map(group=>groupHtml(group,draft)).join('')}
  <section class="navigation-profile-group"><h3>Логические правила</h3><div class="navigation-profile-checkbox-grid">${check(draft,'settings.visibility.usesStealthSkill','Использовать навык скрытности','Применять навык бойца к заметности движения.')}${check(draft,'settings.weapon.allowFireWhileMoving','Разрешить стрельбу в движении','Можно вести огонь без полной остановки.')}${check(draft,'settings.weapon.allowReloadWhileMoving','Разрешить перезарядку','Можно перезаряжаться во время движения.')}${check(draft,'settings.restrictions.allowedWhileSuppressed','Допустимо при подавлении','Профиль остаётся доступным под подавлением.')}</div><div class="movement-profile-select-grid movement-profile-select-grid-spaced">${select('settings.noise.surfacePolicy','Влияние поверхности',[['profile_multiplier','Множитель профиля'],['material_profile_future','Профиль местности']],draft.settings.noise.surfacePolicy)}${select('settings.restrictions.fallbackRule','Правило резервного режима',[['profile','Перейти к резервному профилю'],['slower_gait','Снизить способ движения'],['stop','Остановиться']],draft.settings.restrictions.fallbackRule)}</div></section></main></div>`;
}

function groupHtml([title,description,fields]:MovementEditorGroup,draft:MovementProfile):string{return `<section class="navigation-profile-group"><h3>${title}</h3><p class="movement-profile-group-description">${description}</p><div class="navigation-profile-field-grid">${fields.map(f=>fieldHtml(f,draft)).join('')}</div></section>`;}
function fieldHtml([path,label,help,min,max,step,unit]:MovementEditorField,draft:MovementProfile):string{const value=Number(getPath(draft,path));const standard=Number(getPath(getBuiltInMovementProfile(draft.templateProfileId),path));const extreme=value<=min+(max-min)*.08||value>=max-(max-min)*.08?'Экстремальное значение':'';return `<article class="navigation-profile-field"><div class="navigation-profile-field-title"><strong>${label}</strong><span>${unit}</span></div><p>${help}</p><div class="navigation-profile-field-control"><input aria-label="${esc(label)}: ползунок" type="range" data-movement-number="${esc(path)}" min="${min}" max="${max}" step="${step}" value="${value}"/><input aria-label="${esc(label)}: точное значение" type="number" data-movement-number="${esc(path)}" min="${min}" max="${max}" step="${step}" value="${value}"/><button type="button" data-movement-reset="${esc(path)}" aria-label="Сбросить ${esc(label)}">↺</button></div><div class="navigation-profile-field-meta"><span>Стандарт: ${standard}</span><span data-movement-warning="${esc(path)}">${extreme}</span></div></article>`;}
function profileButton(p:MovementProfile,selectedId:string):string{return `<button type="button" data-movement-profile-id="${esc(p.id)}" class="${p.id===selectedId?'active':''}"><strong>${esc(p.nameRu)}</strong><span>${gaitLabel(p.preferredGait)}${p.builtIn?' · встроенный':' · пользовательский'}</span></button>`;}
function fallbackSelect(registry:MovementProfileRegistry,draft:MovementProfile):string{return `<label class="movement-profile-select"><span>Резервный профиль</span><select data-movement-select="fallbackProfileId"><option value="">Без резервного профиля</option>${registry.listProfiles().filter(p=>p.id!==draft.id).map(p=>`<option value="${esc(p.id)}" ${p.id===draft.fallbackProfileId?'selected':''}>${esc(p.nameRu)}</option>`).join('')}</select><small>Выбирается, когда исходный режим временно недоступен.</small></label>`;}
function button(name:string,label:string,disabled=false,className=''):string{return `<button type="button" data-movement-action="${name}" class="${className}" ${disabled?'disabled':''}>${label}</button>`;}
function select(path:string,label:string,options:readonly(readonly[string,string])[],value:string):string{return `<label class="movement-profile-select"><span>${label}</span><select data-movement-select="${path}">${options.map(([id,textValue])=>`<option value="${id}" ${id===value?'selected':''}>${textValue}</option>`).join('')}</select></label>`;}
function numberInput(path:string,label:string,value:number,min:number,max:number,step:number):string{return `<label class="movement-profile-select"><span>${label}</span><input type="number" data-movement-number="${path}" value="${value}" min="${min}" max="${max}" step="${step}"/></label>`;}
function check(draft:MovementProfile,path:string,label:string,help:string):string{return `<label class="navigation-profile-checkbox"><input type="checkbox" data-movement-checkbox="${path}" ${getPath(draft,path)?'checked':''}/><span><strong>${label}</strong><small>${help}</small></span></label>`;}
function text(path:string,label:string,value:string):string{return `<label><span>${label}</span><input type="text" data-movement-text="${path}" value="${esc(value)}"/></label>`;}
function area(path:string,label:string,value:string):string{return `<label><span>${label}</span><textarea data-movement-area="${path}" rows="2">${esc(value)}</textarea></label>`;}
function gaitLabel(gait:MovementGait):string{return ({walk:'Шаг',crouch_walk:'Пригнувшись',run:'Бег',sprint:'Спринт',crawl:'Ползком'} satisfies Record<MovementGait,string>)[gait];}
function getPath(source:unknown,path:string):unknown{return path.split('.').reduce<unknown>((v,k)=>typeof v==='object'&&v!==null?(v as Record<string,unknown>)[k]:undefined,source);}
function esc(value:string):string{return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]??c));}
