from pathlib import Path

path = Path(__file__).with_name('agent_live_windows_followup_testsfix.py')
content = path.read_text(encoding='utf-8')
marker = "\n\nfor root_name in ('tests', 'scripts'):\n"
if content.count(marker) != 1:
    raise RuntimeError('final evidence scan marker changed unexpectedly')
patch = '''\n\n# Update the AI test-lab source contract after deleting legacy safe positions.\npath = 'scripts/ai_test_lab_smoke.mjs'\ncontent = read(path)\nfor line, label in [\n    ("  'SAFE_SEARCH_RADIUS_METERS',\\n", 'AI lab safe radius expectation'),\n    ("  'bestSafePositions',\\n", 'AI lab safe positions expectation'),\n    ("  'buildBestSafePositionsFromWorldField',\\n", 'AI lab renderer safe scan expectation'),\n    ("  'bestSafePositionScore',\\n", 'AI lab safe score expectations'),\n    ("  'distanceToBestSafePosition',\\n", 'AI lab safe distance expectations'),\n]:\n    content = remove_exact(content, line, label)\nwrite(path, content)\n\n\n# Remove deleted values from the canonical AI dictionary smoke.\npath = 'scripts/ai_dictionary_smoke.mjs'\ncontent = read(path)\ncontent = replace_exact(content, "  'currentPositionDanger', 'currentExpectedProtection', 'bestSafePositionScore',\\n  'distanceToBestSafePosition', 'routeDanger', 'threatConfidence',", "  'currentPositionDanger', 'currentExpectedProtection', 'routeDanger', 'threatConfidence',", 'AI dictionary safe-position values')\nwrite(path, content)\n\n\n# Remove the dedicated combat safe-position scenario while retaining contact, suppression, memory and routing checks.\npath = 'scripts/combat_tactical_integration_smoke.ts'\ncontent = read(path)\ncontent = remove_exact(content, 'verifyRealThreatChangesSafePositions();\\n', 'combat safe-position scenario call')\ncontent = remove_regex(content, r'\\nfunction verifyRealThreatChangesSafePositions\\(\\): void \\{.*?\\n\\}\\n(?=\\nfunction verifyRealThreatChangesRouteCostAndReplan)', 'combat safe-position scenario')\ncontent = replace_exact(content, "console.log('Combat tactical integration smoke passed: 17 subjective contact, evidence memory, suppression, merge, alias, persistence, terrain and route checks.');", "console.log('Combat tactical integration smoke passed: 16 subjective contact, evidence memory, suppression, merge, alias, persistence and route checks.');", 'combat smoke completion count')\nwrite(path, content)\n\n\n# Delete the obsolete standalone winner smoke and remove its workflow path filter.\nlegacy_smoke = ROOT / 'scripts/combat_safe_position_winner_smoke.ts'\nif not legacy_smoke.exists():\n    raise RuntimeError('obsolete combat safe-position winner smoke is missing before deletion')\nlegacy_smoke.unlink()\npath = '.github/workflows/combat-foundation-core.yml'\ncontent = read(path)\ncontent = remove_exact(content, "      - 'scripts/combat_safe_position_winner_smoke.ts'\\n", 'combat workflow obsolete safe-position path')\nwrite(path, content)\n'''
content = content.replace(marker, patch + marker, 1)
path.write_text(content, encoding='utf-8')
print('Removed safe-position expectations and deleted the obsolete standalone winner smoke.')
