import type {
  AmmoDefinitionV1,
  CombatCatalogBundleV1,
  LoadoutTemplateV1,
  WeaponClass,
  WeaponDefinitionV1,
  WeaponProficiency,
} from './CombatCatalogTypes';

export const BUILT_IN_AMMO_DEFINITION_IDS = [
  'ammo_762x54r_ball',
  'ammo_762x25_tokarev',
] as const;

export const BUILT_IN_WEAPON_DEFINITION_IDS = [
  'weapon_mosin_m9130',
  'weapon_ppsh41',
  'weapon_dp27',
] as const;

export const BUILT_IN_LOADOUT_TEMPLATE_IDS = [
  'loadout_rifleman',
  'loadout_submachine_gunner',
  'loadout_machine_gunner',
  'loadout_assistant_machine_gunner',
] as const;

const AMMO: AmmoDefinitionV1[] = [
  {
    schemaVersion: 1,
    ammoDefinitionId: 'ammo_762x54r_ball',
    revision: 1,
    status: 'published',
    nameEn: '7.62×54R ball',
    nameRu: 'Винтовочный патрон 7,62×54R',
    // Prototype tuning values; they are not declared historically exact.
    projectileMassKilograms: 0.0096,
    muzzleVelocityMetersPerSecond: 865,
    bodyPenetrationBudget: 1.15,
    woundEffectMultiplier: 1,
    tracer: false,
    tracerVisualProfileId: null,
    maximumLifetimeSeconds: 6,
  },
  {
    schemaVersion: 1,
    ammoDefinitionId: 'ammo_762x25_tokarev',
    revision: 1,
    status: 'published',
    nameEn: '7.62×25 Tokarev ball',
    nameRu: 'Пистолетный патрон 7,62×25 ТТ',
    // Prototype tuning values; they are not declared historically exact.
    projectileMassKilograms: 0.0055,
    muzzleVelocityMetersPerSecond: 488,
    bodyPenetrationBudget: 0.65,
    woundEffectMultiplier: 0.72,
    tracer: false,
    tracerVisualProfileId: null,
    maximumLifetimeSeconds: 4,
  },
];

const WEAPONS: WeaponDefinitionV1[] = [
  {
    schemaVersion: 1,
    weaponDefinitionId: 'weapon_mosin_m9130',
    revision: 1,
    status: 'published',
    nameEn: 'Mosin M91/30 rifle',
    nameRu: 'Винтовка Мосина обр. 1891/30',
    weaponClass: 'rifle',
    ammo: { definitionId: 'ammo_762x54r_ball', revision: 1 },
    availableFireModes: ['single'],
    roundsPerMinute: 45,
    shortBurstRounds: 1,
    longBurstRounds: 1,
    capacityRounds: 5,
    baseDispersionRadians: 0.0018,
    aimQualityPerSecond: 0.55,
    recoilPitchRadiansPerShot: 0.025,
    recoilYawRadiansPerShot: 0.009,
    recoilRecoveryPerSecond: 0.8,
    readySeconds: 0.7,
    recoverySeconds: 0.35,
    reloadStages: [
      { stageId: 'open', kind: 'open', durationSeconds: 0.3, interruptible: true, movementAllowed: false, loadedRoundsAppliedAtCompletion: false },
      { stageId: 'load', kind: 'load', durationSeconds: 2.4, interruptible: true, movementAllowed: false, loadedRoundsAppliedAtCompletion: true },
      { stageId: 'close', kind: 'close', durationSeconds: 0.35, interruptible: true, movementAllowed: false, loadedRoundsAppliedAtCompletion: false },
    ],
    allowFireWhileMoving: false,
    movingDispersionMultiplier: 2.5,
    postureDispersionMultiplier: { standing: 1, crouched: 0.78, prone: 0.55 },
    deploySeconds: 0.45,
    undeploySeconds: 0.3,
    deployedTraverseArcRadians: Math.PI * 2,
    undeployedSustainedFireMultiplier: 1,
    assistantDeployMultiplier: 1,
    assistantReloadMultiplier: 1,
    soundRadiusMeters: 450,
    muzzleFlashVisibility: 0.7,
    muzzleForwardOffsetMeters: 0.8,
  },
  {
    schemaVersion: 1,
    weaponDefinitionId: 'weapon_ppsh41',
    revision: 1,
    status: 'published',
    nameEn: 'PPSh-41 submachine gun',
    nameRu: 'Пистолет-пулемёт Шпагина ППШ-41',
    weaponClass: 'submachine_gun',
    ammo: { definitionId: 'ammo_762x25_tokarev', revision: 1 },
    availableFireModes: ['single', 'short_burst', 'long_burst', 'suppress'],
    roundsPerMinute: 900,
    shortBurstRounds: 4,
    longBurstRounds: 10,
    capacityRounds: 35,
    baseDispersionRadians: 0.0045,
    aimQualityPerSecond: 0.72,
    recoilPitchRadiansPerShot: 0.013,
    recoilYawRadiansPerShot: 0.014,
    recoilRecoveryPerSecond: 1.15,
    readySeconds: 0.45,
    recoverySeconds: 0.22,
    reloadStages: [
      { stageId: 'open', kind: 'open', durationSeconds: 0.2, interruptible: true, movementAllowed: true, loadedRoundsAppliedAtCompletion: false },
      { stageId: 'load', kind: 'load', durationSeconds: 2.3, interruptible: true, movementAllowed: false, loadedRoundsAppliedAtCompletion: true },
      { stageId: 'close', kind: 'close', durationSeconds: 0.2, interruptible: true, movementAllowed: true, loadedRoundsAppliedAtCompletion: false },
    ],
    allowFireWhileMoving: true,
    movingDispersionMultiplier: 2.2,
    postureDispersionMultiplier: { standing: 1, crouched: 0.82, prone: 0.7 },
    deploySeconds: 0.35,
    undeploySeconds: 0.25,
    deployedTraverseArcRadians: Math.PI * 2,
    undeployedSustainedFireMultiplier: 1,
    assistantDeployMultiplier: 1,
    assistantReloadMultiplier: 1,
    soundRadiusMeters: 300,
    muzzleFlashVisibility: 0.8,
    muzzleForwardOffsetMeters: 0.58,
  },
  {
    schemaVersion: 1,
    weaponDefinitionId: 'weapon_dp27',
    revision: 1,
    status: 'published',
    nameEn: 'DP-27 light machine gun',
    nameRu: 'Ручной пулемёт ДП-27',
    weaponClass: 'machine_gun',
    ammo: { definitionId: 'ammo_762x54r_ball', revision: 1 },
    availableFireModes: ['single', 'short_burst', 'long_burst', 'suppress'],
    roundsPerMinute: 550,
    shortBurstRounds: 3,
    longBurstRounds: 8,
    capacityRounds: 47,
    baseDispersionRadians: 0.003,
    aimQualityPerSecond: 0.45,
    recoilPitchRadiansPerShot: 0.022,
    recoilYawRadiansPerShot: 0.016,
    recoilRecoveryPerSecond: 0.72,
    readySeconds: 0.9,
    recoverySeconds: 0.4,
    reloadStages: [
      { stageId: 'open', kind: 'open', durationSeconds: 0.45, interruptible: true, movementAllowed: false, loadedRoundsAppliedAtCompletion: false },
      { stageId: 'load', kind: 'load', durationSeconds: 3.2, interruptible: true, movementAllowed: false, loadedRoundsAppliedAtCompletion: true },
      { stageId: 'close', kind: 'close', durationSeconds: 0.4, interruptible: true, movementAllowed: false, loadedRoundsAppliedAtCompletion: false },
    ],
    allowFireWhileMoving: false,
    movingDispersionMultiplier: 3,
    postureDispersionMultiplier: { standing: 1.3, crouched: 1, prone: 0.62 },
    deploySeconds: 1.6,
    undeploySeconds: 1.1,
    deployedTraverseArcRadians: Math.PI * 0.75,
    undeployedSustainedFireMultiplier: 0.55,
    assistantDeployMultiplier: 0.72,
    assistantReloadMultiplier: 0.68,
    soundRadiusMeters: 500,
    muzzleFlashVisibility: 0.9,
    muzzleForwardOffsetMeters: 0.82,
  },
];

const UNTRAINED: Record<WeaponClass, WeaponProficiency> = {
  rifle: 'untrained',
  submachine_gun: 'untrained',
  machine_gun: 'untrained',
  pistol: 'untrained',
};

function proficiency(trained: WeaponClass, specialist = false): Record<WeaponClass, WeaponProficiency> {
  return { ...UNTRAINED, [trained]: specialist ? 'specialist' : 'trained' };
}

const LOADOUTS: LoadoutTemplateV1[] = [
  {
    schemaVersion: 1,
    loadoutTemplateId: 'loadout_rifleman',
    revision: 1,
    status: 'published',
    nameEn: 'Rifleman',
    nameRu: 'Стрелок',
    primary: { definition: { definitionId: 'weapon_mosin_m9130', revision: 1 }, loadedRounds: 5 },
    secondary: null,
    reserveRoundsByAmmoDefinitionId: { ammo_762x54r_ball: 60 },
    maximumReserveRoundsByAmmoDefinitionId: { ammo_762x54r_ball: 90 },
    firstAidCharges: 1,
    role: 'rifleman',
    proficiencyByWeaponClass: proficiency('rifle'),
  },
  {
    schemaVersion: 1,
    loadoutTemplateId: 'loadout_submachine_gunner',
    revision: 1,
    status: 'published',
    nameEn: 'Submachine gunner',
    nameRu: 'Автоматчик',
    primary: { definition: { definitionId: 'weapon_ppsh41', revision: 1 }, loadedRounds: 35 },
    secondary: null,
    reserveRoundsByAmmoDefinitionId: { ammo_762x25_tokarev: 140 },
    maximumReserveRoundsByAmmoDefinitionId: { ammo_762x25_tokarev: 210 },
    firstAidCharges: 1,
    role: 'submachine_gunner',
    proficiencyByWeaponClass: proficiency('submachine_gun'),
  },
  {
    schemaVersion: 1,
    loadoutTemplateId: 'loadout_machine_gunner',
    revision: 1,
    status: 'published',
    nameEn: 'Machine gunner',
    nameRu: 'Пулемётчик',
    primary: { definition: { definitionId: 'weapon_dp27', revision: 1 }, loadedRounds: 47 },
    secondary: null,
    reserveRoundsByAmmoDefinitionId: { ammo_762x54r_ball: 141 },
    maximumReserveRoundsByAmmoDefinitionId: { ammo_762x54r_ball: 235 },
    firstAidCharges: 1,
    role: 'machine_gunner',
    proficiencyByWeaponClass: proficiency('machine_gun', true),
  },
  {
    schemaVersion: 1,
    loadoutTemplateId: 'loadout_assistant_machine_gunner',
    revision: 1,
    status: 'published',
    nameEn: 'Assistant machine gunner',
    nameRu: 'Помощник пулемётчика',
    primary: { definition: { definitionId: 'weapon_mosin_m9130', revision: 1 }, loadedRounds: 5 },
    secondary: null,
    reserveRoundsByAmmoDefinitionId: { ammo_762x54r_ball: 188 },
    maximumReserveRoundsByAmmoDefinitionId: { ammo_762x54r_ball: 282 },
    firstAidCharges: 1,
    role: 'assistant_machine_gunner',
    proficiencyByWeaponClass: { ...proficiency('rifle'), machine_gun: 'trained' },
  },
];

export function createDefaultCombatCatalogBundle(): CombatCatalogBundleV1 {
  return clone({
    formatVersion: 1,
    revision: 1,
    ammoDefinitions: AMMO,
    weaponDefinitions: WEAPONS,
    loadoutTemplates: LOADOUTS,
  });
}

function clone<T>(value: T): T {
  return structuredClone(value);
}
